language: php

php:
  - 5.3
  - 5.4

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit --configuration LmMvcTests\phpunit.xml LmMvcTests

notifications:
    on_success: never
    on_failure: always