<?php
namespace LmMvc;

/**
 * Class DefaultExceptionHandler
 *
 * The default exception handler.
 *
 * @package LmMvc
 */
class DefaultExceptionHandler implements ExceptionHandler
{
    /**
     * Handles any thrown exceptions (such as those generated by LMMVC or by the application itself).
     * 
     * @param \Exception $ex
     * @param bool $internal
     */
    public function handle(\Exception $ex, $internal = true)
    {

    }
} 